ckanHelmValues:
  ckan:
    replicaCount: 1

  monitoring:
    enabled: true

datagovukHelmValues:
  find:
    replicaCount: 1

  monitoring:
    enabled: true

dguSharedHelmValues:
  config:
    rateLimitCount: "100"
    rateLimitPeriod: "60"
  redis:
    replicaCount: 1
